/**
 * Tool response helpers — shared text/error wrappers.
 *
 * Generated by scripts/apply-sector-regulator-golden-standard.py.
 */

export function textContent(data: unknown) {
  return {
    content: [{ type: "text" as const, text: JSON.stringify(data, null, 2) }],
  };
}

export function errorContent(message: string) {
  return {
    content: [{ type: "text" as const, text: message }],
    isError: true as const,
  };
}
