/**
 * about — Server identity, version, data sources, and tool catalog.
 *
 * Generated by scripts/apply-sector-regulator-golden-standard.py from sources.yml + package.json.
 * To update, edit sources.yml or package.json and re-run the helper.
 */

import { TOOL_NAMES } from "./registry.js";

export type AboutInput = Record<string, never>;

const SERVER_NAME = "norwegian-data-protection-mcp";
const VERSION = "0.1.0";
const DESCRIPTION = "Datatilsynet (Norwegian data protection authority) MCP server — decisions, sanctions, and guidance on GDPR enforcement in Norway";
const JURISDICTION = "Norway";
const CATEGORY = "data-protection";

const SOURCES_SUMMARY: Array<{ name: string; url: string; license: string }> = [
    {
      name: "Datatilsynet (Norwegian Data Protection Authority)",
      url: "https://www.datatilsynet.no/",
      license: "Public Domain (Norwegian government publications)",
    },
    {
      name: "Lovdata (Norwegian Legal Information)",
      url: "https://lovdata.no/",
      license: "Public Domain (Norwegian legislation)",
    },
  ];

export async function about(
  _input: AboutInput,
): Promise<{
  name: string;
  version: string;
  description: string;
  jurisdiction: string;
  category: string;
  sources: Array<{ name: string; url: string; license: string }>;
  tools: string[];
  disclaimer: string;
  _metadata: { tool: string };
}> {
  return {
    name: SERVER_NAME,
    version: VERSION,
    description: DESCRIPTION,
    jurisdiction: JURISDICTION,
    category: CATEGORY,
    sources: SOURCES_SUMMARY,
    tools: [...TOOL_NAMES],
    disclaimer:
      "This is a research tool, not legal or compliance advice. Verify critical citations against authoritative sources.",
    _metadata: { tool: "about" },
  };
}
