/**
 * check_data_freshness — Per-source data age and staleness flags.
 *
 * Reads `last_verified` baked in at install time from sources.yml. Threshold
 * defaults to 90 days for sector-regulator data (typical update_frequency
 * is quarterly per sources.yml). Override via the `threshold_days` input.
 *
 * Generated by scripts/apply-sector-regulator-golden-standard.py from sources.yml.
 * To update, edit sources.yml and re-run the helper.
 */

export interface CheckDataFreshnessInput {
  source?: string;
  threshold_days?: number;
}

interface BakedSource {
  name: string;
  authority: string;
  last_verified: string | null;
}

interface SourceFreshness {
  source: string;
  authority: string;
  last_verified: string;
  age_days: number | null;
  status: "fresh" | "stale" | "unknown";
  threshold_days: number;
}

const DEFAULT_THRESHOLD_DAYS = 90;

const SOURCES: BakedSource[] = [
    {
      name: "Datatilsynet (Norwegian Data Protection Authority)",
      authority: "Datatilsynet",
      last_verified: "2026-05-10",
    },
    {
      name: "Lovdata (Norwegian Legal Information)",
      authority: "Lovdata",
      last_verified: "2026-05-10",
    },
  ];

export async function checkDataFreshness(
  input: CheckDataFreshnessInput,
): Promise<{
  overall_status: "fresh" | "stale" | "unknown";
  sources: SourceFreshness[];
  checked_at: string;
  _metadata: { tool: string };
}> {
  const checkedAt = new Date().toISOString();
  const threshold = input.threshold_days ?? DEFAULT_THRESHOLD_DAYS;
  const filter = input.source?.toLowerCase();

  const filtered = filter
    ? SOURCES.filter(
        (s) =>
          s.name.toLowerCase().includes(filter) ||
          s.authority.toLowerCase().includes(filter),
      )
    : SOURCES;

  const freshnessList: SourceFreshness[] = filtered.map((s) => {
    const ageDays = computeAgeDays(s.last_verified);

    let status: "fresh" | "stale" | "unknown";
    if (ageDays === null) {
      status = "unknown";
    } else if (ageDays > threshold) {
      status = "stale";
    } else {
      status = "fresh";
    }

    return {
      source: s.name,
      authority: s.authority,
      last_verified: s.last_verified ?? "unknown",
      age_days: ageDays,
      status,
      threshold_days: threshold,
    };
  });

  const statuses = freshnessList.map((f) => f.status);
  let overall: "fresh" | "stale" | "unknown";
  if (statuses.includes("stale")) {
    overall = "stale";
  } else if (statuses.length === 0 || statuses.every((s) => s === "unknown")) {
    overall = "unknown";
  } else {
    overall = "fresh";
  }

  return {
    overall_status: overall,
    sources: freshnessList,
    checked_at: checkedAt,
    _metadata: { tool: "check_data_freshness" },
  };
}

function computeAgeDays(dateStr: string | null): number | null {
  if (!dateStr) return null;
  const then = new Date(dateStr).getTime();
  if (Number.isNaN(then)) return null;
  return Math.floor((Date.now() - then) / (1000 * 60 * 60 * 24));
}
