/**
 * list_sources — Expose data provenance metadata as an MCP tool.
 *
 * Returns information about the authoritative data sources backing this server,
 * including coverage, freshness, and licensing.
 *
 * Generated by scripts/apply-sector-regulator-golden-standard.py from sources.yml.
 * To update, edit sources.yml and re-run the helper.
 */

export type ListSourcesInput = Record<string, never>;

interface SourceInfo {
  name: string;
  authority: string;
  url: string;
  license: string;
  coverage: string;
  languages: string[];
  last_verified: string | null;
}

const MCP_NAME = "Norwegian Data Protection MCP";
const JURISDICTION = "Norway";

const SOURCES: SourceInfo[] = [
    {
      name: "Datatilsynet (Norwegian Data Protection Authority)",
      authority: "Datatilsynet",
      url: "https://www.datatilsynet.no/",
      license: "Public Domain (Norwegian government publications)",
      coverage: "Overtredelsesgebyr, vedtak, klagevedtak, irettesettelser, forbud, varsler, veiledere, rapporter, hoeringsuttalelser, verktoy",
      languages: ["no"],
      last_verified: "2026-05-10",
    },
    {
      name: "Lovdata (Norwegian Legal Information)",
      authority: "Lovdata",
      url: "https://lovdata.no/",
      license: "Public Domain (Norwegian legislation)",
      coverage: "Personopplysningsloven, forskrift om behandling av personopplysninger (referenced, not included)",
      languages: ["no"],
      last_verified: "2026-05-10",
    },
  ];

export async function listSources(
  _input: ListSourcesInput,
): Promise<{
  mcp_name: string;
  jurisdiction: string;
  sources: SourceInfo[];
  _metadata: { tool: string; source_authority: string };
}> {
  return {
    mcp_name: MCP_NAME,
    jurisdiction: JURISDICTION,
    sources: SOURCES,
    _metadata: {
      tool: "list_sources",
      source_authority: SOURCES.map((s) => s.authority).join(", "),
    },
  };
}
