/**
 * Tool registry — wires up all tools for ListTools + CallTool handlers.
 *
 * Generated by scripts/apply-sector-regulator-golden-standard.py.
 * To update, edit src/index.ts (existing tools) or sources.yml (meta-tools)
 * and re-run the helper.
 */

import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import type { Server } from "@modelcontextprotocol/sdk/server/index.js";

import { handleSearchDecisions, SEARCH_DECISIONS_TOOL } from "./search-decisions.js";
import { handleGetDecision, GET_DECISION_TOOL } from "./get-decision.js";
import { handleSearchGuidelines, SEARCH_GUIDELINES_TOOL } from "./search-guidelines.js";
import { handleGetGuideline, GET_GUIDELINE_TOOL } from "./get-guideline.js";
import { handleListTopics, LIST_TOPICS_TOOL } from "./list-topics.js";

import { listSources } from "./list-sources.js";
import { about } from "./about.js";
import { checkDataFreshness } from "./check-data-freshness.js";

export const TOOLS = [
  SEARCH_DECISIONS_TOOL,
  GET_DECISION_TOOL,
  SEARCH_GUIDELINES_TOOL,
  GET_GUIDELINE_TOOL,
  LIST_TOPICS_TOOL,
  {
    name: "list_sources",
    description:
      "List the authoritative data sources backing this MCP server, including coverage, licensing, and last-verified date per source. No arguments required.",
    inputSchema: { type: "object" as const, properties: {}, required: [] },
  },
  {
    name: "about",
    description:
      "Server identity, version, jurisdiction, source summary, and tool catalog. No arguments required.",
    inputSchema: { type: "object" as const, properties: {}, required: [] },
  },
  {
    name: "check_data_freshness",
    description:
      "Report per-source data age and flag staleness against a threshold (default 90 days). Use `source` to filter by name/authority substring; use `threshold_days` to override the staleness cutoff.",
    inputSchema: {
      type: "object" as const,
      properties: {
        source: {
          type: "string",
          description: "Optional substring to filter sources by name or authority.",
        },
        threshold_days: {
          type: "number",
          description: "Days after last_verified at which a source is considered stale. Default 90.",
        },
      },
      required: [],
    },
  },
];

export const TOOL_NAMES: readonly string[] = TOOLS.map((t) => t.name);

import { textContent, errorContent } from "./_helpers.js";

export function registerTools(server: Server): void {
  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: TOOLS,
  }));

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const { name, arguments: args = {} } = request.params;

    try {
      switch (name) {
        case "search_decisions":
          return await handleSearchDecisions(args);

        case "get_decision":
          return await handleGetDecision(args);

        case "search_guidelines":
          return await handleSearchGuidelines(args);

        case "get_guideline":
          return await handleGetGuideline(args);

        case "list_topics":
          return await handleListTopics(args);

        case "list_sources":
          return textContent(await listSources({} as never));

        case "about":
          return textContent(await about({} as never));

        case "check_data_freshness":
          return textContent(await checkDataFreshness(args as { source?: string; threshold_days?: number }));

        default:
          return errorContent(`Unknown tool: ${name}`);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return errorContent(`Error in ${name}: ${message}`);
    }
  });
}

